type Gender = "WOMEN" | "MEN" | "UNISEX";

export type CatalogProduct = {
  name: string;
  slug: string;
  description: string;
  sku: string;
  price: string;
  salePrice?: string;
  category: string;
  gender: Gender;
  stock: number;
  colors: string[];
  featured?: boolean;
  newArrival?: boolean;
  image: string;
};

export const catalogProducts: CatalogProduct[] = [
  {
    name: "Çantë flap me zinxhir",
    slug: "quilted-chain-flap-bag",
    description:
      "Çantë e kompaktë me qepje diamanti dhe rrip lëkure me zinxhir. Mjaft e strukturuar për mbrëmje, e lehtë për ditën. Brenda hyjnë telefoni, portofoli i vogël dhe çelësat.",
    sku: "IVA-BAG-001",
    price: "79.00",
    category: "bags",
    gender: "WOMEN",
    stock: 12,
    colors: ["E zezë", "Krem"],
    featured: true,
    newArrival: true,
    image: "bag-quilted-black.png",
  },
  {
    name: "Portofol me zinxhir, krem",
    slug: "cream-quilted-wallet-on-chain",
    description:
      "Portofol i hollë me zinxhir në ngjyrë krem. Mbajeni crossbody ose si clutch. Për mbrëmje dhe ditë udhëtimi, kur doni më pak — por të mbajtur bukur.",
    sku: "IVA-BAG-002",
    price: "69.00",
    category: "bags",
    gender: "WOMEN",
    stock: 10,
    colors: ["Krem"],
    featured: true,
    image: "bag-quilted-cream.png",
  },
  {
    name: "Portofol me zinxhir, i zi",
    slug: "black-quilted-wallet-on-chain",
    description:
      "Versioni i zi i portofolit me zinxhir. Qepje diamanti, detaje të arta dhe rrip i gërshetuar me lëkurë.",
    sku: "IVA-BAG-003",
    price: "69.00",
    category: "bags",
    gender: "WOMEN",
    stock: 9,
    colors: ["E zezë"],
    image: "bag-quilted-woc-black.png",
  },
  {
    name: "Mini çantë me dorezë",
    slug: "structured-mini-top-handle",
    description:
      "Mini çantë e saktë me dorezë, në lëkurë me efekt saffiano taupe. Kyç i artë, rrip spalle opsional dhe siluetë që e mban formën.",
    sku: "IVA-BAG-004",
    price: "89.00",
    salePrice: "79.00",
    category: "bags",
    gender: "WOMEN",
    stock: 7,
    colors: ["Taupe", "Portokalli"],
    featured: true,
    newArrival: true,
    image: "bag-structured-taupe.png",
  },
  {
    name: "Çantë me dorezë, portokalli",
    slug: "orange-structured-top-handle",
    description:
      "Çantë e strukturuar me dorezë në lëkurë me efekt saffiano. Portokallia e zgjedhur është editoriale, jo e zhurmshme.",
    sku: "IVA-BAG-005",
    price: "95.00",
    category: "bags",
    gender: "WOMEN",
    stock: 6,
    colors: ["Portokalli"],
    featured: true,
    image: "bag-structured-orange.png",
  },
  {
    name: "Crossbody prej xhinsi",
    slug: "denim-canvas-crossbody",
    description:
      "Crossbody e kompaktë prej kanavace xhinsi me detaje lëkure dhe tokëz përpara. E lehtë, praktike, për çdo ditë.",
    sku: "IVA-BAG-006",
    price: "59.00",
    category: "bags",
    gender: "UNISEX",
    stock: 11,
    colors: ["Xhinse"],
    newArrival: true,
    image: "bag-denim-crossbody.png",
  },
  {
    name: "Hobo e butë, burgundi",
    slug: "burgundy-soft-hobo",
    description:
      "Hobo e butë në burgundi me zinxhir sipër dhe doreza të shkurtra. Strukturë e butë, hapje e gjerë, detaje të thjeshta.",
    sku: "IVA-BAG-007",
    price: "55.00",
    category: "bags",
    gender: "WOMEN",
    stock: 8,
    colors: ["Burgundi"],
    featured: true,
    image: "bag-hobo-burgundy.png",
  },
  {
    name: "Çantë spalle lakuriqe",
    slug: "patent-shoulder-bag",
    description:
      "Çantë spalle e zezë lakuriqe me kapëse të artë skulpturore. E kompaktë, për mbrëmje, e lehtë për ta mbajtur në dorë.",
    sku: "IVA-BAG-008",
    price: "72.00",
    category: "bags",
    gender: "WOMEN",
    stock: 5,
    colors: ["E zezë"],
    image: "bag-patent-shoulder.png",
  },
  {
    name: "Vanity me monogram",
    slug: "monogram-vanity-case",
    description:
      "Vanity me strukturë të fortë, dorezë sipër, zinxhir dhe gjuhëz lëkure. Si mini çantë ose organizuese e strukturuar.",
    sku: "IVA-BAG-009",
    price: "75.00",
    category: "bags",
    gender: "WOMEN",
    stock: 8,
    colors: ["Monogram"],
    image: "bag-monogram-vanity.png",
  },
  {
    name: "Mini tote me monogram",
    slug: "monogram-mini-tote",
    description:
      "Tote e kompaktë me doreza lëkure dhe detaje të arta. I pret të nevojshmet e ditës pa vëllimin e një shopperi të madh.",
    sku: "IVA-BAG-010",
    price: "82.00",
    category: "bags",
    gender: "WOMEN",
    stock: 9,
    colors: ["Monogram"],
    featured: true,
    image: "bag-monogram-tote.png",
  },
  {
    name: "Boston prej kanavace",
    slug: "canvas-boston-bag",
    description:
      "Boston e vogël në kanavacë të veshur, me doreza lëkure dhe rrip të shkëputshëm. E strukturuar, me zinxhir, për ditët në qytet.",
    sku: "IVA-BAG-011",
    price: "68.00",
    category: "bags",
    gender: "UNISEX",
    stock: 10,
    colors: ["Kafe"],
    image: "bag-canvas-boston.png",
  },
  {
    name: "Satchel e strukturuar, bezhë",
    slug: "beige-structured-satchel",
    description:
      "Satchel me rrip në kanavacë të veshur bezhë dhe doreza lëkure të lëmuara. Përmasë e qytetit, vijë e pastër.",
    sku: "IVA-BAG-012",
    price: "74.00",
    category: "bags",
    gender: "WOMEN",
    stock: 7,
    colors: ["Bezhë"],
    image: "bag-structured-beige.png",
  },
  {
    name: "Mini flap me monogram",
    slug: "monogram-mini-flap",
    description:
      "Çantë e vogël flap në kanavacë me monogram dhe rrip të gjerë të shkëputshëm. Si çantë bel, crossbody ose clutch.",
    sku: "IVA-BAG-013",
    price: "64.00",
    category: "bags",
    gender: "WOMEN",
    stock: 12,
    colors: ["Monogram"],
    newArrival: true,
    image: "bag-monogram-mini.png",
  },
  {
    name: "Kuti vanity",
    slug: "signature-vanity-box",
    description:
      "Kuti vanity me zinxhir rreth e rrotull, dorezë sipër dhe rrip të gjatë. E kompaktë, e drejtë dhe e organizuar.",
    sku: "IVA-BAG-014",
    price: "61.00",
    category: "bags",
    gender: "WOMEN",
    stock: 8,
    colors: ["Kafe"],
    image: "bag-signature-vanity.png",
  },
  {
    name: "Syze pa kornizë me krahë druri",
    slug: "rimless-wood-temple-sunglasses",
    description:
      "Syze drejtkëndëshe pa kornizë, me krahë me efekt druri dhe detaje të arta. Kornizë e rafinuar për femra dhe meshkuj.",
    sku: "IVA-SUN-001",
    price: "49.00",
    salePrice: "42.00",
    category: "sunglasses",
    gender: "UNISEX",
    stock: 14,
    colors: ["Burgundi", "E artë"],
    featured: true,
    newArrival: true,
    image: "sunglasses-rimless.png",
  },
  {
    name: "Portofol kompakt",
    slug: "compact-fold-wallet",
    description:
      "Portofol i vogël treshe në lëkurë të zezë me kokrrizë. Fole për karta, ndarje për kartëmonedha dhe pllakë e artë e pastër.",
    sku: "IVA-WAL-001",
    price: "32.00",
    category: "wallets",
    gender: "UNISEX",
    stock: 18,
    colors: ["E zezë"],
    featured: true,
    image: "bag-structured-beige.png",
  },
  {
    name: "Kolier me perla",
    slug: "pearl-collar-necklace",
    description:
      "Kolier i ngushtë me perla të barabarta dhe kapëse të artë në qendër. Rri te baza e qafës, mbi këmishë ose fustan.",
    sku: "IVA-JWL-001",
    price: "39.00",
    category: "jewelry",
    gender: "WOMEN",
    stock: 15,
    colors: ["Perla", "E artë"],
    featured: true,
    image: "jewelry-pearl-choker.png",
  },
  {
    name: "Varëse me hallka",
    slug: "link-pendant-necklace",
    description: "Zinxhir i hollë me varëse ovale të ndërlidhura. Në përfundim të artë ose të argjendtë.",
    sku: "IVA-JWL-002",
    price: "24.00",
    category: "jewelry",
    gender: "WOMEN",
    stock: 20,
    colors: ["E artë", "E argjendtë"],
    featured: true,
    image: "jewelry-link-pendants.png",
  },
  {
    name: "Set me varëse trekëndëshe",
    slug: "triangle-pendant-set",
    description:
      "Varëse dhe byzylyk i përputhur, me zinxhir kubanez dhe pllakë trekëndëshe. Vishen së bashku ose veç e veç.",
    sku: "IVA-JWL-003",
    price: "29.00",
    category: "jewelry",
    gender: "UNISEX",
    stock: 12,
    colors: ["E artë"],
    image: "jewelry-triangle-set.png",
  },
  {
    name: "Byzylyk me katërfletësha",
    slug: "clover-station-bracelet",
    description:
      "Byzylyk me motive katërfletëshi në smalt dhe të artë. Zgjidhni ngjyrën që rri qetë me gardërobën tuaj.",
    sku: "IVA-JWL-004",
    price: "22.00",
    category: "jewelry",
    gender: "WOMEN",
    stock: 25,
    colors: ["E zezë", "E bardhë", "E gjelbër", "Të përziera"],
    featured: true,
    image: "jewelry-clover-station.png",
  },
  {
    name: "Byzylyk me motiv katërfletëshi",
    slug: "clover-motif-bracelet",
    description:
      "Byzylyk i hollë me katërfletësha në të artë, smalt dhe motive me teksturë. I lehtë në kyç, me përmasa të kujdesshme.",
    sku: "IVA-JWL-005",
    price: "19.00",
    category: "jewelry",
    gender: "WOMEN",
    stock: 22,
    colors: ["E zezë", "E kaltër", "E gjelbër", "E bardhë"],
    image: "jewelry-clover-bracelets.png",
  },
  {
    name: "Varëse me katërfletësha",
    slug: "clover-station-necklace",
    description:
      "Varëse më e gjatë me katërfletësha në të zezë, të bardhë dhe të artë. Rri te kocka e qafës.",
    sku: "IVA-JWL-006",
    price: "27.00",
    category: "jewelry",
    gender: "WOMEN",
    stock: 16,
    colors: ["E zezë", "E bardhë", "E artë"],
    image: "jewelry-clover-necklaces.png",
  },
  {
    name: "Varëse me gur të gjelbër",
    slug: "emerald-halo-pendant",
    description: "Gur i gjelbër në qendër, i rrethuar me shkëlqim, në zinxhir të hollë. Në të artë ose të argjendtë.",
    sku: "IVA-JWL-007",
    price: "28.00",
    category: "jewelry",
    gender: "WOMEN",
    stock: 14,
    colors: ["E artë", "E argjendtë"],
    newArrival: true,
    image: "jewelry-emerald-pendants.png",
  },
  {
    name: "Set tennis me kristale",
    slug: "crystal-tennis-set",
    description:
      "Varëse, choker tennis dhe vathë me kristale të rrumbullakëta. Për mbrëmje si set, ose veç e veç.",
    sku: "IVA-JWL-008",
    price: "45.00",
    category: "jewelry",
    gender: "WOMEN",
    stock: 9,
    colors: ["E argjendtë"],
    featured: true,
    image: "jewelry-crystal-set.png",
  },
  {
    name: "Set me medalione",
    slug: "coin-pendant-layering-set",
    description: "Dy medalione në zinxhirë të hollë, për t’u veshur së bashku. Një varëse e qetë për çdo ditë.",
    sku: "IVA-JWL-009",
    price: "21.00",
    category: "jewelry",
    gender: "UNISEX",
    stock: 17,
    colors: ["E artë"],
    image: "jewelry-coin-pendants.png",
  },
  {
    name: "Varëse rrethore me panter",
    slug: "panther-circle-pendant",
    description: "Varëse rrethore me profil panteri, në zinxhir të hollë. Në të artë ose të argjendtë.",
    sku: "IVA-JWL-010",
    price: "26.00",
    category: "jewelry",
    gender: "WOMEN",
    stock: 11,
    colors: ["E artë", "E argjendtë"],
    image: "jewelry-panther-pendants.png",
  },
  {
    name: "Vathë rrethorë",
    slug: "circle-logo-stud-earrings",
    description: "Vathë rrethorë të hapur me vijë të hollë. Të lehtë, për çdo ditë, me siluetë të qartë.",
    sku: "IVA-JWL-011",
    price: "16.00",
    category: "jewelry",
    gender: "WOMEN",
    stock: 20,
    colors: ["E artë"],
    image: "jewelry-circle-studs.png",
  },
];
